# This Configuration is intended for Ubuntu and used in 22.04 version!
---
- hosts: servers
  become: true
  vars:
    created_username: admin
    ssh_public_key_path: /Desktop/Ansible/Syncerland/ssh-keys/id_ed25519.pub
    name_server_1: 10.202.10.202
    name_server_2: 10.202.10.102

  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
        cache_valid_time: 3600

      tags:
        - user
        - tools
        - firewall
        - dns
        - docker

  tasks:
    - name: Create User
      include_tasks:
        file: tasks/create-user.yml
        apply:
          tags:
            - user
      tags:
        - user

    - name: Install Tools
      include_tasks:
        file: tasks/install-tools.yml
        apply:
          tags:
            - tools
      tags:
        - tools

    - name: Config Firewall
      include_tasks:
        file: tasks/firewall.yml
        apply:
          tags:
            - firewall
      tags:
        - firewall

    - name: Config DNS
      include_tasks:
        file: tasks/dns.yml
        apply:
          tags:
            - dns
      tags:
        - dns

    - name: Install Docker
      include_tasks:
        file: tasks/docker.yml
        apply:
          tags:
            - docker
      tags:
        - docker
