- name: Install required Ansible packages for Docker
  apt:
      pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
      state: latest
      update_cache: true

- name: Install Docker and Docker compose
  apt:
      pkg:
          - docker.io
          - docker-compose-v2
